export class StoredProcedure {
    private hasNotStoredProcedure = "Não tem stored procedure";

    private storedProcedureMap = new Map([
        ["/Agenda/GetAgenda", "GetAgenda"],
        ["/Agenda/GetAgendaAnoMes", "GetAgendaAnoMes"],
        ["/Api/AcessaTrilha", "AcessaTrilha"],
        ["/api/AcessoCursoOnline", "GetLinkCurso"],
        ["/Api/AlteraStatusUsuario", "AlteraStatusUsuario"],
        ["/api/AlternativaAvaliacao", "GetAlternativasAvaliacao"],
        ["/api/AlternativaPesquisa", "GetAlternativasPesquisa"],
        ["/Api/Aniversariantes", "GetAniversariantesDia"],
        ["/Api/AoVivo", "GetAoVivo"],
        ["/api/Arquivo", "GetArquivos"],
        ["/api/ArquivoAprovar", "AprovaArquivo"],
        ["/api/ArquivoAvaliar", "AvaliaArquivo"],
        ["/api/ArquivoComentar", "ArquivoComentar"],
        ["/api/ArquivoDetalhe", "GetDetalhesArquivo"],
        ["/api/ArquivoSugerir", "SugereArquivo"],
        ["/api/AtividadeRoteiro", "GetAtividadesRoteiro"],
        ["/api/AtividadesPlanoDesenvolvimento", "GET GetAtividadesGrupoPlano | POST AlteraStatusAtividadePlano"],
        ["/Api/AtividadesTrilha", "GetAtividadesTrilha"],
        ["/api/AtualizaCertificadoAtividade", "AtualizaCertificadoAtividade"],
        ["/api/AtualizaCertificadoGratuito", "AtualizaCertificadoGratuito"],
        ["/Api/AtualizaEmail", "AtualizaEmail"],
        ["/Api/AtualizaPresencasInstrutorTurmaPresencial", "AtualizaPresencaCursosPresenciaisInstrutor"],
        ["/api/Avaliacao", "GetAvaliacoes"],
        ["/api/AvaliacaoCurso", "GET GetAvaliacaoCurso | POST AvaliaCurso"],
        ["/api/AvaliacaoCursoPresencial", "AvaliaCursoPresencial"],
        ["/api/AvaliacaoKenoby", "InsereAvaliacaoKenoby | SalvaTentativaEnvioKenoby"],
        ["/api/AvaliacaoPesquisa", "AvaliaPesquisa"],
        ["/api/AvaliacaoQuestionario", "GetAvaliacaoQuestionario"],
        ["/api/AvaliacaoQuestoes", "GetAvaliacao"],
        ["/api/AvaliacaoReacaoEstatistica", "GetReacaoPorc"],
        ["/api/AvaliacaoReacaoLider", "GetAvaliacaoReacaoLider"],
        ["/api/AvaliarAvaliacao", "AvaliaAvaliacao"],
        ["/api/BaixouArquivo", "BaixouArquivo"],
        ["/api/BookMark", "GET GetBookmarks | POST GravaBookmark"],
        ["/api/BuscaPlantao", "BuscaPlantao"],
        ["/Api/BuscaPlantaoTodos", "BuscaPlantaoTodos"],
        ["/Api/BuscaPlantaoTodosProximo", "BuscaPlantaoTodosProximo"],
        ["/api/BuscaProfissional", "BuscaProfissional"],
        ["/Api/BuscaUsuario", "BuscaUsuario"],
        ["/api/BuscaUsuarioSugestao", "BuscaUsuSugestao"],
        ["/api/CategoriaArquivo", "GetCategoriasArquivo"],
        ["/api/CategoriaAvaliacao", "GetCategoriasAvaliacao"],
        ["/api/CategoriaCurso", "GetCategorias"],
        ["/api/CategoriaFaq", "GetCategoriasFaq"],
        ["/api/CategoriaPesquisa", "GetCategoriasPesquisa"],
        ["/Api/CategoriasChamado", "GetCategoriasChamado"],
        ["/Api/CategoriasGrupo", "GetCategoriasGrupo"],
        ["/Api/CategoriasTrilha", "GetCategoriasTrilha"],
        ["/api/CertificadoCurso", "GetCertificadoCurso"],
        ["/api/CertificadosAtividade", "GetCertificadosAtividade"],
        ["/api/CertificadosGratuitos", "GetCertificadosGratuitos"],
        ["/api/CheckIn", "PlantaoCheckIn"],
        ["/api/CheckOut", "PlantaoCheckOut"],
        ["/api/ColaboradorAmbientacao", "GetColaboradorAmbientacao"],
        ["/Api/ComentaChamado", "ComentaChamado"],
        ["/api/ComentarioArquivo", "GET GetComentariosArquivo | POST InsereComentarioArquivo"],
        ["/api/ComentarioAvaliacao", "GET GetComentarioAvalicao | POST ComentaAvaliacao"],
        ["/api/ComentarioCurso", "GET GetComentarioCurso | POST ComentaCurso | DELETE ExcluiComentario"],
        ["/api/ComentarioCursoPresencial", "ComentaCursoPresencial"],
        ["/api/ComentarioPesquisa", "ComentaPesquisa"],
        ["/api/Compartilhamento", "GET GetCompartilhamentos | POST GravaCompartilhamento"],
        ["/api/CompartilhamentoAbrir", "AbreCompartilhamento"],
        ["/api/CompartilhamentoCategoria", "EditaCategoriaCompartilhamento"],
        ["/api/CompartilhamentoComentario", "GET GetComentarioCompartilhamento | POST ComentaCompartilhamento"],
        ["/api/CompartilhamentoComite", "GetCompartilhamentosComite"],
        ["/api/CompartilhamentoCurtidas", "CurteCompartilhamento"],
        ["/api/CompartilhamentoDenuncia", "DenunciaCompartilhamento"],
        ["/api/CompartilhamentoDenunciaAnalise", "GravaAnaliseDenuncia"],
        ["/api/CompartilhamentoFiltrar", "FiltraCompartilhamentos"],
        ["/api/CompartilhamentoOficializa", "OficializaCompartilhamento"],
        ["/api/CompartilhamentoQuestoes", "GetQuestoesCompartilhadas"],
        ["/api/CompartilhamentoTemaDenunciado", "GetTemasDenunciados"],
        ["/api/CompartilhamentoTipo", "GetTipoCompartilhamento"],
        ["/api/ConferenciaConfig", this.hasNotStoredProcedure],
        ["/api/Configuracao", "GetConfiguracao"],
        ["/Api/ConfiguracaoLogin", "SP_CONFIG_LOGIN"],
        ["/api/Conhecimento", "GetNomeConhecimento"],
        ["/api/ConhecimentoCertificado", "GetConhecimentosCertificados"],
        ["/api/ConhecimentoTipo", "GetTipoConhecimento"],
        ["/Api/Conteudos", "GetConteudos"],
        ["/api/ControleVersao", "GetVersaoMinima"],
        ["/Api/CriaSenha", "CriaSenha"],
        ["/api/Curso", "GetCurso"],
        ["/Api/CursoCurtida", "SP_INSERE_REACAO"],
        ["/api/CursoDownload", "GetCurso"],
        ["/api/CursoPresencial", "GET GetCursoPresencial | POST InsereCursoPresencial | AtualizaCursoPresencial"],
        ["/api/CursoPresencialCategoria", "GetCategoriasPresencial"],
        ["/api/CursoPresencialTodos", "GetCursosPresenciais"],
        ["/Api/Cursos", "GetCursos"],
        ["/Api/CursosGratuitos", "GetCursosGratuitos"],
        ["/api/CursosJornada", "GetCursosJornada"],
        ["/Api/CursosLider", "GetCursosLider"],
        ["/api/CursosMaisAcessados", "GetCursosMaisAcessados"],
        ["/Api/CursosObrigatorios", "GetCursosObrigatorios"],
        ["/Api/CursosWebinar", "GetWebinar"],
        ["/api/CurtidaArquivo", "InsereCurtirArquivo"],
        ["/api/DadoCorportativo", "GetDadosCorporativo"],
        ["/api/DadoRealizacao", "GravaDadosRealizacao"],
        ["/api/DadosCurtidas", "GetQuemCurtiu"],
        ["/api/DadosEquipeTecnico", "GetDadosEquipeTecnicos"],
        ["/Api/DashBoardGrafico", "GetDashBoardGrafico"],
        ["/Api/DashBoardLider", "GetDashBoardLider"],
        ["/Api/DashBoardParametros", "GetDashBoardParametros"],
        ["/Api/DashBoardTabela", "GetDashBoardTabela"],
        ["/Api/DeletaCompartilhamento", "DeletaCompartilhamento"],
        ["/api/Depoimento", "GET GetDepoimentos | POST AlteraDepoimento | CriaDepoimento"],
        ["/api/DepoimentoAprovar", "AprovaDepoimento"],
        ["/api/Destaques", "GetDestaques"],
        ["/Api/DetalhePrograma", "DetalhesPrograma"],
        ["/Api/DetalhesAoVivo", "GetDetalhesAoVivo"],
        ["/api/DivisoesUsuarios", "GetDivisoesUsuarios"],
        ["/Api/Elos/AlteraStatusAtividade", "AlteraStatusAtividadePlanoElos"],
        ["/Api/Elos/AtividadesPlanoUsuario", "GetAtividadesPlano"],
        ["/Api/Elos/DetalhesArquivo", "GetDetalhesArquivo"],
        ["/Api/Elos/DetalhesPlanoUsuario", "GetDetalhesPlanoUsu"],
        ["/Api/Elos/Planos", "GetPlanosElos"],
        ["/Api/Elos/PlanoUsuario", "GetPlanoUsuElos"],
        ["/Api/Elos/Ranking", "GetRankingElo"],
        ["/api/Enquete", "GetEnquetes | GetDetalhesEnquete | GetEnqueteDestaque"],
        ["/api/EnqueteResposta", "GET GetRespostasEnquete | POST RespondeEnquete"],
        ["/Api/EnviaAvaliacaoKenoby", "GetAvaliacoesKenoby"],
        ["/api/EnviaEmail", this.hasNotStoredProcedure],
        ["/Api/EnviaSenhaTempEmailSMS", "GeraSenhaTemporariaMedico"],
        ["/Api/EsqueciSenha", "EsqueciSenha"],
        ["/Api/EsqueciSenhaEmail", "ConfirmaDadosUsu"],
        ["/api/EventoTurmaPresencial", "InsereEventoTurmaPresencial | AtualizaEventoTurmaPresencial"],
        ["/api/ExcelRelat", "GetTemasBuscados"],
        ["/Api/Externo/CertificadoCurso", "InsereCertificadoExterno"],
        ["/Api/Externo/Certificados", "GetCertificadosExternos"],
        ["/Api/Externo/Cursos", "GetCursosExternos"],
        ["/Api/Externo/Formacao", "InsereFormacao"],
        ["/Api/Externo/Matricular", "MatriculaCursoExterno"],
        ["/Api/Externo/TipoFormacao", "GetTiposFormacao"],
        ["/api/ExtratoPontos", "GetExtratoPontos"],
        ["/Api/FaleConosco", "CriaSolicitacao"],
        ["/api/Faq", "GetFaqs | GetFaq"],
        ["/api/FaqPergunta", "GravaPergunta"],
        ["/api/FaqResposta", "GravaResposta"],
        ["/api/Farejador", this.hasNotStoredProcedure],
        ["/api/FarolDesktop", "GetFarolDesktop"],
        ["/api/FinalizarEventoTurmaPresencial", "FinalizaEventoTurmaPresencial"],
        ["/api/FinalizarTurmaPresencial", "FinalizaTurmaPresencial"],
        ["/Api/FixarCompartilhamento", "GetTimeline"],
        ["/api/Forum", "GetForuns | GetDetalhesForum | GetForumDestaque"],
        ["/api/ForumIndicar", "IndicaForum"],
        ["/api/ForumMensagem", "GET GetMensagens | POST CriaMensagem | DELETE DeletaMensagem"],
        ["/api/ForumMensagemComentario", "GetComentariosMensagens"],
        ["/api/Gabarito", "GravaGabarito"],
        ["/api/GetArquivosCurso", "GetArquivosCurso"],
        ["/Api/GetAvaliacoesKenoby", "GetRealizacoesKenoby"],
        ["/Api/GetCatGrupoPlano", "GetCatGrupoPlano"],
        ["/api/GetCertificadoCurso", "AcessoDiretoCursoCertificado"],
        ["/Api/GetChamados", "GetChamados"],
        ["/api/GetCursoUsuario", "GetCursoUsuario"],
        ["/api/GetEstruturaCadastro", "GetEstruturaCadastro"],
        ["/Api/GetInstrutorTurmaPresencial", "GetUsuariosCursosPresenciaisInstrutor"],
        ["/api/GetLikeCurso", "GetLikeCurso"],
        ["/api/GetLinkExterno", "GetLinkExterno"],
        ["/api/GetRelatorioUnificado", "GetRelatoriosUnificados"],
        ["/Api/GetTipoConhecimentoUsu", "GetTipoConhecimentoUsu"],
        ["/Api/GravaDadosUsuario", "GravaDadosUsuario"],
        ["/Api/GravaInscricaoGratuito", "GravaInscricaoGratuito"],
        ["/api/GravaNotificacao", this.hasNotStoredProcedure],
        ["/Api/GravaVisualizacaoCompartilhamento", "GravaCompartilhamentoVisualizacao"],
        ["/api/GrupoAtividadePlano", "GetGrupoAtividadesPlano"],
        ["/api/GrupoPlano", "GetGrupoPlano"],
        ["/Api/Grupos", "GetGrupos"],
        ["/Api/GruposCategoria", "GetGruposCategoria"],
        ["/Api/GruposDetalhes", "GetGrupoDetalhes"],
        ["/api/Historico", "GetHistorico"],
        ["/api/IndicacoesCursoEquipe", "GetIndicacoesMinhaEquipe"],
        ["/api/IndicacoesCursoPares", "GetIndicacoesPares"],
        ["/api/IndicarAvaliacao", "IndicaAvaliacao"],
        ["/Api/IndicarCompartilhamento", "IndicaCompartilhamento"],
        ["/api/IndicarCurso", "IndicaCurso | IndicaSerie"],
        ["/api/IndicarCursoPresencial", "IndicaCursoPresencial"],
        ["/api/IndicarPesquisa", "IndicaPesquisa"],
        ["/api/InfoConteudo", "GetConteudo"],
        ["/api/InscricaoParticipante", "InscreveParticipante"],
        ["/api/InscricaoTurmaPresencial", "GravaInscricaoPresencial"],
        ["/api/InsereLikeCurso", "InsereLikeCurso"],
        ["/Api/InsereParticipanteInstrutorTurmaPresencial", "InsereUsuariosCursosPresenciaisInstrutor"],
        ["/Api/InsereParticipanteInstrutorTurmaPresencialCracha", "InsereUsuariosCursosPresenciaisInstrutorCracha"],
        ["/api/Interacao", "GravaInteracao"],
        ["/api/InteracaoPlantao", "InteracaoPlantao"],
        ["/api/InteracaoPlantaoLista", "GetInteracaoPlantao"],
        ["/api/ItemCurso", "GetItemCurso"],
        ["/api/ItemCursoPreRequisito", "GetPreRequisitoItem"],
        ["/api/Jornada", "GetJornada"],
        ["/Api/Klabin/Usuario", "GetDadosUsu"],
        ["/api/ListaPerguntaGrupoFaq", "GetPerguntaGrupoFaq"],
        ["/api/ListaUnidades", "GetMatrizes"],
        ["/Api/ListInstrutorTurmasPresenciais", "GetTurmasCursosPresenciaisInstrutor"],
        ["/api/Material", "GetMateriais"],
        ["/api/Matricula", "MatriculaCurso"],
        ["/Api/MatriculasCursosUsuario", "SP_GET_MATRICULAS"],
        ["/api/Matriz", "GetMatrizes"],
        ["/api/MatrizCargo", "GetMatrizesCargo"],
        ["/api/MatrizNivel", "GetMatrizesNivel"],
        ["/api/MatrizSeguranca", "GetMatrizSeguranca"],
        ["/api/MatrizUnidade", "GetMatrizesUnidade"],
        ["/api/MatrizUnidadeCargo", "GetMatrizUnidadeCargo"],
        ["/Api/MensagensChamado", "GetComentariosChamado"],
        ["/api/Menu", "GetMenuUsu"],
        ["/api/MeuDesenvolvimento", "GetMeuDesenvolvimento"],
        ["/api/MeusPlantoes", "MeusPlantoes"],
        ["/api/MinhaConquista", "GetMinhasConquistas"],
        ["/api/MotivosDenuncia", "GetMotivosDenuncia"],
        ["/api/Objetivo", "GravaObjetivo"],
        ["/api/Pagina", "GetPagina"],
        ["/api/PaginaPublica", "GetPagina"],
        ["/Api/Parcerias", "GetParcerias"],
        ["/api/PegaPlantao", "PegaPlantao"],
        ["/api/Perfil", "GET GetPerfil | POST AlteraPerfil"],
        ["/api/PerfilLider", "GetPerfilLider"],
        ["/api/PerfilSobre", "AlteraPerfil"],
        ["/Api/PerfilUsuario", "GetPerfil"],
        ["/Api/PerguntasSecretas", "GetPerguntasSecretas"],
        ["/api/Pesquisa", "GetPesquisa"],
        ["/Api/PesquisaJornada", "GetPesqJournada"],
        ["/Api/Pesquisas", "GetPesquisas"],
        ["/api/PilarCursoPresencial", "InserePilarCursoPresencial"],
        ["/api/Ponto", "GetMeusPontos"],
        ["/api/PontosUsuario", "GetPontosUsuarios"],
        ["/api/Populares", "GetPopulares"],
        ["/api/PortaArquivos", "GetPortaArquivos"],
        ["/api/Presencas", "GravaPresencas"],
        ["/api/Programas", "GetProgramas"],
        ["/Api/ProvaPratica/ListaProvasPraticas", "GetProvasPraticas"],
        ["/Api/ProvaPratica/ListaUsuarios", "GetListaUsuProvaPratica"],
        ["/Api/ProvaPratica/ProvaPraticaUsuario", "GetProvaPraticaUsu"],
        ["/api/QstRealizacoes", "GetRealizacoes"],
        ["/api/QstVector", "GetQstVector"],
        ["/api/QuestaoOficializa", "OficializaQuestao"],
        ["/api/Questoes", "GET GetQuestoes | POST GravaQuestao"],
        ["/api/QuestoesPesquisa", "GetQuestoesPesquisa"],
        ["/api/Ranking", "GetRanking"],
        ["/api/RankingArea", "GetRankingArea"],
        ["/api/RankingGestor", "GetRankingGestores"],
        ["/api/RankingMinhaEquipe", "GetRankingMinhaEquipe"],
        ["/api/RealidadeAumentada", "GetARs"],
        ["/api/RealizacaoAvaliacao", "GravaRealizacaoAvaliacao"],
        ["/api/RealizacaoPesquisa", "GravaRealizacaoPesquisa"],
        ["/api/Recomendacao", "GetRecomendacoes"],
        ["/Api/RecuperaSenhaSMS", "GeraSenhaTemporariaMedico"],
        ["/api/Recurso", "BuscaRecursos"],
        ["/api/Recurso/BuscarRecursosLider", "BuscaRecursosLider"],
        ["/api/Recurso/BuscarRecursosTag", "BuscaRecursosTag"],
        ["/api/RecursoCurtidas", "CurteRecurso"],
        ["/api/Regras", "GetRegrasMedalhas"],
        ["/api/RegraSenha", "RegraSenha"],
        ["/api/RequisitoCurso", "VerificaRequisitoCurso"],
        ["/api/RespostaComentario", "GET GetRespostasComentario | POST RespostaComentario"],
        ["/api/RespostaPesquisa", "GravaRespostasPesquisa"],
        ["/api/ResumoDadosCorporativos", "GetResumoDadosCorporativo"],
        ["/Api/ReunioesAgendadas", "GetAoVivo"],
        ["/Api/ReunioesInstantaneas", "GetAoVivo"],
        ["/api/RoteiroAprovacao", "GravaAprovacaoRoteiro"],
        ["/api/RoteiroAtualColaborador", "GetRoteiroAtualColaborador"],
        ["/api/Secoes", "GetSecoes"],
        ["/api/Segmentacao", "CriaSegmentacao"],
        ["/api/Seguidores", "GET GetSeguidores | POST InsereSeguidor"],
        ["/api/Seguidores/Delete", "DeletaSeguidor"],
        ["/api/Seguindo", "GetSeguindo"],
        ["/api/Solicitacao", this.hasNotStoredProcedure],
        ["/api/TemasAcessados", "GetTemasAcessados"],
        ["/api/TemasBuscados", "GetTemasBuscados"],
        ["/api/TemasCertificadosBottom", "GetBottomTemasCertificados"],
        ["/api/TemasCertificadosTop", "GetTopTemasCertificados"],
        ["/api/TemasNaoEncontrados", "GetTemasNaoEncontrados"],
        ["/api/TermoAceite", "GET GetTermoAceite | POST GravaTermoAceite"],
        ["/api/TimeLine", "GetTimeline"],
        ["/api/TipoDocumento", "GetTipoDocumento"],
        ["/api/token", "AutenticaUsuario | AutenticaUsuarioToken"],
        ["/api/Trilha", "GetMinhaTrilha"],
        ["/Api/TrilhaCargoUsu", "GetTrilhas"],
        ["/api/TrilhaEquipe", "GetTrilhaEquipe"],
        ["/Api/Trilhas", "GetTrilhas"],
        ["/Api/TrilhasCategoria", "GetTrilhasCategoria"],
        ["/Api/TrilhasDetalhe", "GetTrilhaDetalhe"],
        ["/api/TrilhaUsuarioEquipe", "SP_GET_EQUIPE_INTEIRA"],
        ["/Api/TrocaSenha", "TrocaSenha"],
        ["/api/TurmasPresenciais", "GET GetTurmasCursosPresenciais | POST InsereTurmaPresencial | " +
            "AtualizaTurmaPresencial"],
        ["/Api/TurmasWebinar", "GetTurmasWebinar"],
        ["/Api/Ucchl/ConfirmaDadosSenha", "ConfirmaDadosSenha"],
        ["/Api/Ucchl/CriaSenha", "CriaSenhaPernambucanas"],
        ["/Api/Ucchl/DetalheColaborador", "GetDetalhesColaboradorEquipe"],
        ["/Api/Ucchl/MinhaEquipe", "GetMinhaEquipe"],
        ["/Api/Ucchl/TrocaSenha", "TrocaSenha"],
        ["/api/Usuario", "GetDadosUsu"],
        ["/Api/Usuario", "GetDadosUsu"],
        ["/api/UsuarioAderente", "GetUsuariosAderentes"],
        ["/Api/UsuarioGNDI", "GetDadosUsu"],
        ["/Api/VerificaConclusaoAtividadeTrilha", "VerificaConclusaoAtividadeTrilha"],
        ["/Api/VerificaDadosUsuSenha", "VerificaDadosUsuSenha"],
        ["/Api/VerificaPontuacaoTrilha", "VerificaPontuacaoTrilha"],
        ["/api/Video", "GetVideos | GetVideo"],
        ["/api/VideoAprovar", "AprovaVideo"],
        ["/api/VideoAvaliar", "AvaliaVideo"],
        ["/api/VideoComentario", "ComentaVideo"],
        ["/Api/VideoFixo", "GetVideoFixo"],
        ["/api/VideoSugerir", "SugereVideo"],
        ["/api/VideoVisualizar", "GravaVisualizacao"],
        ["/api/VisualizaPlantao", "VisualizaPlantao"],
        ["/Avaliacao/GetHistoricoAvaliacoes", "GetHistoricoAvaliacao"],
        ["/Certificado/ProgramaExpansao", "GetCertificadoTrilha"],
        ["/Cracha/GetCracha", "GetCracha"],
        ["/GetAcessoDiretoConflitoInteresse", "AcessoDiretoConflitoInteresse"],
        ["/Item/GetDetalhesItem", "GetDetalhesItem"],
        ["/Notificacao/GetNotificacao", "GetNotificacao"],
        ["/Notificacao/GetNotificacoesUsu", "GetNotificacoesUsu"],
        ["/Notificacao/GetQuantidadeNotificacao", "GetQuantidadeNotificacao"],
        ["/Regras/GetRegrasPontuacao", "GetRegrasPontuacao"],
        ["/Vimeo/AlteraUrlArquivo", "GetUrlVimeoArquivo & AlteraUrlArquivo"],
        ["/Vimeo/AlteraUrlCompartilhamento", "GetUrlVimeo & AlteraUrlCompartilhamento"],
        ["/api/AtualizaDadosUsu", "AtualizaDadosUsu"],
        ["/api/PerfilSobreCaigetec", "AtualizaPerfil"],
        ["/Api/TrilhaResumo", "GetResumoTrilha"],
    ]);

    public get(endpoint: string): string {
        return this.storedProcedureMap.get(endpoint) || "";
    }
}